<div  style="background-color:#66439A; text-align: center; font-family: 'Courier New', sans-serif;" class="header">
<div class="header">
  <br>
  <h1> <b>Tutorial </b></h1>
  <p>A step-by-step guidance to DrMD package.</p>
  <br>
</div>


<div  style="color:#66439A; font-family: 'Courier New', sans-serif;">
<h3>Introduction</h3>

Welcome to DrMD package! This user-friendly package is the perfect first step for anyone interested in Quantum Computing. Working with 2-qubit systems exclusively, this package ensures simplicity for beginners. Let's get started!

In [ ]:
from qubit_state import QubitState
from unitary_gate import UnitaryGate
import gate_list as gl
from circuit import Circuit
import numpy as np

<div  style="color:#66439A; font-family: 'Courier New', sans-serif;">
<br>
<h2> <b>Qubit States</b>  </h2> 
<br>
</div>

We can create a new qubit state using the matrix representation with <code>QubitState()</code>. Let the first qubit be in the $|0\rangle$ state while the second qubit in the $|1\rangle$ - this corresponds to the matrix $[0, 1, 0, 0]$. Otherwise, we can also create this qubit by inputing two single-qubit matrices $[1,0], [0,1]$.

In [103]:
qb1 = QubitState([0, 1, 0, 0])
qb2 = QubitState([1, 0], (0, 1))

Using the <code>peek()</code> function, we can check that these two states are the same.

In [120]:
print("This is the first state: ", qb1.peek())
print("This is the second state: ", qb2.peek())

This is the first state:  [0 1 0 0]
This is the second state:  [0 1 0 0]


Normalisation is an essential thing in Quantum Mechanics! However, this package is very user-friendly, so this is not required when inputting an array to create a qubit - the function will do it for you.

In [121]:
qb = QubitState([1, 1, 1, 1])
print("The state is normalised: ", qb)

The state is normalised:  [0.5 0.5 0.5 0.5]


<!-- <div  style="color:#FFC145; font-family: 'Courier New', sans-serif;"> -->
<div  style="color:#66439A; font-family: 'Courier New', sans-serif;">
<h3>Measure a Qubit State</h3>

 With a qubit in hand (?), the simplest thing one can do is to measure it. With <code>DrMD</code>, there are two ways of measuring a qubit. Note that the measurement is done in the computational basis (Z-basis).
 1. Using <code>measure_collapse()</code> function which mimics the collapse of the state upon being measured. This returns an eigenstate. 
 2. Using <code>measure_stats()</code> function which does not collapse the state. Instead, this function will return the probability with which the initial state collapses to a certain eigenstate.

For example, let initialise our qubits in the state $|\psi_0\rangle = \frac{1}{2}(|00\rangle + |10\rangle + |01\rangle + |11\rangle)$.

We see that <code>measure_collapse()</code> collapes the state $|\psi_0\rangle$ into the state $|00\rangle$ (or $|10\rangle, |01\rangle, |11\rangle$) with a 25% probability.


In [122]:
qb = QubitState([1, 1, 1, 1])
print("The initial state is: ", qb.peek())
qb.measureCollapse()
print("The collapsed state is: ", qb.peek())

The initial state is:  [0.5 0.5 0.5 0.5]
The collapsed state is:  [1 0 0 0]


Moreover, we can use <code>to_measure</code> parameter to specify the qubit on which we are doing partial measurement. For example, in this case, we are doing partial measurement on the first qubit. We see that the function returns the state $|0 0 1 1\rangle$ (or $|1 1 0 0\rangle$) 50% of the time.

In [125]:
qb = QubitState([1, 1, 1, 1])
print("The initial state is: ", qb.peek())
qb.measureCollapse(to_measure=1)
print("The collapsed state (when measuring the 1st qubit) is: ", qb.peek())

The initial state is:  [0.5 0.5 0.5 0.5]
The collapsed state (when measuring the 1st qubit) is:  [0.70710678 0.70710678 0.         0.        ]


We see that <code>measure_stats()</code> returns an array indicating which state and with what probability our initial $|\psi_0\rangle$ would collapse to, without actually collapsing it.

In [ ]:
qb = QubitState([1, 1, 1, 1])
print("The initial statistics is: \n", qb.measureStats())
print(
    "The measurement statistics (when measuring the 1st qubit) is: \n ",
    qb.measureStats(to_measure=1),
)

The initial statistics is: 
 [([1 0 0 0], 0.25), ([0 1 0 0], 0.25), ([0 0 1 0], 0.25), ([0 0 0 1], 0.25)]
The measurement statistics (when measuring the 1st qubit) is: 
  [([0.7071 0.7071 0.     0.    ], 0.5), ([0.     0.     0.7071 0.7071], 0.5)]


<div  style="color:#66439A; font-family: 'Courier New', sans-serif;">
<h2><b> Unitary Gates </b></h2>

What better fun can one have with qubits than applying unitary gates to them? Nothing! That's why package <code>DrMD</code> is here to provide you nerds with the greatest fun of your life with UnitaryGate class.

One can create new unitary gates using their matrix representation, with a 4 x 4 matrix or with two 2 x 2 matrices, each denoting a gate on a qubit. Let's try to create a $X_1Z_2$ gate and see its action on the state $|00\rangle$.

In [ ]:
x1z2 = UnitaryGate([[0, 1], [1, 0]], [[1, 0], [0, -1]])

In [130]:
# Define state |00>
qb00 = QubitState([1, 0, 0, 0])
qb = x1z2.apply(qb00)
print("Apply X1Z2 on the |00> state: ", qb)

Apply X1Z2 on the |00> state:  [0 0 1 0]


If one is too lazy, one can also use our predefined list of Pauli gates. For example, to create $X_1Z_2$ gate, we can do as follows.

In [133]:
mat = UnitaryGate(gl.X_mat, gl.Z_mat)
print("Are the two Unitary Gates the same? ", x1z2.compare(mat))

Are the two Unitary Gates the same?  True


Apply a wrong gate and want to ctrl-z? Fret not! Use <code>dagger()</code> to apply the inverse gate.

In [116]:
x1z2.dagger().apply(qb)

[1 0 0 0]

We see that we get back the initial state $|00\rangle$.

<div  style="color:#66439A; font-family: 'Courier New', sans-serif;">
<br>
<h2><b>Circuits</b></h2>
<br>
</div>

Let's take a step further! A curious mind may ask: "What happens if one has many gates?" The answer is what we are looking at in this section - a circuit!

In [ ]:
c = Circuit([x1z2, gl.hadamard1])

Let's see what this circuit does to our old friend $|00\rangle$.

In [139]:
print("Apply the circuit, the final state is ", c.apply(qb00))

Apply the circuit, the final state is  [ 0.7071  0.     -0.7071  0.    ]


It returns $\frac{1}{\sqrt{2}}(|00\rangle - |10\rangle)$, as expected. There are many other things we can do to an existing circuit. We can <code>append</code> to add or <code>pop</code> to remove the last element, and many more. Let's try them out by preparing an entangled state. We can start from $|00\rangle$ and edit our current circuit.

In [ ]:
c = Circuit([x1z2, gl.hadamard1])
c.insert(1, gl.y2)
c.append(gl.cnot)
c_extra = Circuit([gl.hadamard1, gl.x2, gl.hadamard2])
c.merge(c_extra)
c.pop()
c.isEmpty()
print("The number of gates in the circuit is: ", c.size())
print(str(c))

The number of gates in the circuit is:  6
The gates applied are: 
[[ 0  0  1  0]
 [ 0  0  0 -1]
 [ 1  0  0  0]
 [ 0 -1  0  0]], 
[[0.+0.j 0.-1.j 0.+0.j 0.-0.j]
 [0.+1.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.-0.j 0.+0.j 0.-1.j]
 [0.+0.j 0.+0.j 0.+1.j 0.+0.j]], 
[[ 0.70710678  0.          0.70710678  0.        ]
 [ 0.          0.70710678  0.          0.70710678]
 [ 0.70710678  0.         -0.70710678 -0.        ]
 [ 0.          0.70710678 -0.         -0.70710678]], 
[[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]], 
[[ 0.70710678  0.          0.70710678  0.        ]
 [ 0.          0.70710678  0.          0.70710678]
 [ 0.70710678  0.         -0.70710678 -0.        ]
 [ 0.          0.70710678 -0.         -0.70710678]], 
[[0 1 0 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]].



To wrap this up, let's take a look at an ubiquitous circuit in Quantum Computing.


<div  style="color:#FFC145; text-align: center; font-family: 'Courier New', sans-serif;">
<!-- <div  style="color:#66439A; font-family: 'Courier New', sans-serif;"> -->
<h3><i>Phase kick-back</i></h3>

Also sometimes known as the <i>Hadamard test</i>, the circuit consists of a controlled-unitary sandwiched between two Hadamard gates. In this specific circuit shown below, <i>phase kick-back</i> is a way to introduce a phase in the first qubit. However, there are many cases where this is used to do measurement read-out on an ancilla qubit in order to find an expectation value of a particular observable. 

This is a great time to both show the method as well as for our users here to familiarise ourselves with this package!

![Cute Cat](phase.png)


The schemaic diagram above (taken from online notes by Professor Artur Ekert (https://qubit.guide/qubit_guide.pdf), U here represents the phase gate) shows the circuit to implement <i>phase kick-back</i>. Taking the intial state to be $|01\rangle$, we have

\begin{align*}
    |00\rangle &\xrightarrow{X_2} |11\rangle \\
    &\xrightarrow{H_1} \frac{1}{\sqrt{2}}(|01\rangle + |11\rangle) \\
    &\xrightarrow{C-U} \frac{1}{\sqrt{2}}(|01\rangle + e^{i\varphi}|11\rangle) \\
    &\xrightarrow{H_1} \frac{e^{i\frac{\varphi}{2}}}{2}(\cos{\frac{\varphi}{2}}|0\rangle - i\sin{\frac{\varphi}{2}}|1\rangle)|1\rangle \\
\end{align*}
Measuring the 2nd qubit (i.e. the ancilla), we have introduced a phase in the first qubit. We see that 
$$\mathbb{P}(|01\rangle) = \cos^2{\frac{\varphi}{2}}$$
$$\mathbb{P}(|11\rangle) = \sin^2{\frac{\varphi}{2}}$$

Taking $\varphi = \frac{\pi}{3}$, we will test this circuit with this package.

In [229]:
# Define the controlled-phase gate
phi = np.pi / 3
phase = np.matrix([[1, 0], [0, np.exp(1j * phi)]])
cphase = (
    1 / 2
    * (np.kron((gl.I_mat + gl.Z_mat), gl.I_mat) + np.kron((gl.I_mat - gl.Z_mat), phase))
)
cphase_gate = UnitaryGate(cphase)

# Phase kickback circuit
circ = Circuit([gl.x2, gl.hadamard1, cphase_gate, gl.hadamard1])
qb00 = QubitState([1, 0, 0, 0])

# Measure the state in the 2nd qubit (i.e. the ancilla) to "kickback" the phase to the 1st qubit
qb = circ.apply(qb00).measureCollapse(to_measure=2)
print("This is the initial state: ", qb00.peek())
print(qb.measureStats())

This is the initial state:  [1 0 0 0]
[([0 1 0 0], (0.75-0j)), ([0 0 0 1], (0.25+0j))]


c:\Users\Pham Nguyet Chi Mai\Desktop\UCL\SE_project\DrMD\qubit_state.py:271: ComplexWarning: Casting complex values to real discards the imaginary part
  self.__qb_matrix = np.random.choice(states, p=probs).peek()


Using <code>measure_stats()</code>, we see that the probability is what we expect.

<div  style="color:#FFC145; text-align: center; font-family: 'Courier New', sans-serif;">
<!-- <div  style="color:#66439A; font-family: 'Courier New', sans-serif;"> -->
<h3><i>The end.</i></h3>